CATALOG = [
    {"id":"c001","name":"Mochi Blob","rarity":"common","weight":650,"emoji":"🫧","power":21,"luck":35,"set":"Genesis"},
    {"id":"c002","name":"Byte Bug","rarity":"common","weight":650,"emoji":"🐛","power":27,"luck":31,"set":"Genesis"},
    {"id":"c003","name":"Pocket Cloud","rarity":"common","weight":650,"emoji":"☁️","power":18,"luck":44,"set":"Genesis"},
    {"id":"c004","name":"Noodle Ghost","rarity":"common","weight":650,"emoji":"👻","power":25,"luck":29,"set":"Genesis"},
    {"id":"c005","name":"Toastling","rarity":"common","weight":650,"emoji":"🍞","power":23,"luck":36,"set":"Genesis"},
    {"id":"c006","name":"Pebbo","rarity":"common","weight":650,"emoji":"🐾","power":12,"luck":18,"set":"Genesis"},
    {"id":"c007","name":"Jelly Orbit","rarity":"common","weight":650,"emoji":"🪐","power":29,"luck":34,"set":"Genesis"},
    {"id":"c008","name":"Pixel Sprout","rarity":"common","weight":650,"emoji":"🌱","power":19,"luck":45,"set":"Genesis"},
    {"id":"c009","name":"Static Hamster","rarity":"common","weight":650,"emoji":"🐹","power":26,"luck":38,"set":"Genesis"},
    {"id":"c010","name":"Soda Imp","rarity":"common","weight":650,"emoji":"🥤","power":31,"luck":27,"set":"Genesis"},
    {"id":"r001","name":"Bubble Goblin","rarity":"rare","weight":313,"emoji":"🧌","power":61,"luck":64,"set":"Chaos"},
    {"id":"r002","name":"Laser Raccoon","rarity":"rare","weight":313,"emoji":"🦝","power":58,"luck":67,"set":"Chaos"},
    {"id":"r003","name":"Moon Pigeon","rarity":"rare","weight":313,"emoji":"🕊️","power":53,"luck":72,"set":"Chaos"},
    {"id":"r004","name":"Neon Snail","rarity":"rare","weight":313,"emoji":"🐌","power":48,"luck":77,"set":"Chaos"},
    {"id":"r005","name":"Disco Frog","rarity":"rare","weight":312,"emoji":"🐸","power":62,"luck":58,"set":"Chaos"},
    {"id":"r006","name":"Caffeine Bat","rarity":"rare","weight":312,"emoji":"🦇","power":64,"luck":55,"set":"Chaos"},
    {"id":"r007","name":"404 Cat","rarity":"rare","weight":312,"emoji":"🐈","power":59,"luck":69,"set":"Chaos"},
    {"id":"r008","name":"Tiny Kraken","rarity":"rare","weight":312,"emoji":"🐙","power":66,"luck":52,"set":"Chaos"},
    {"id":"e001","name":"Chrome Yeti","rarity":"epic","weight":134,"emoji":"🦍","power":81,"luck":75,"set":"Afterglow"},
    {"id":"e002","name":"Dream Fox","rarity":"epic","weight":134,"emoji":"🦊","power":77,"luck":82,"set":"Afterglow"},
    {"id":"e003","name":"Void Duck","rarity":"epic","weight":133,"emoji":"🦆","power":79,"luck":79,"set":"Afterglow"},
    {"id":"e004","name":"Turbo Sloth","rarity":"epic","weight":133,"emoji":"🦥","power":85,"luck":70,"set":"Afterglow"},
    {"id":"e005","name":"Prism Moth","rarity":"epic","weight":133,"emoji":"🦋","power":74,"luck":86,"set":"Afterglow"},
    {"id":"e006","name":"Quantum Capybara","rarity":"epic","weight":133,"emoji":"🦫","power":83,"luck":74,"set":"Afterglow"},
    {"id":"l001","name":"Aurum","rarity":"legendary","weight":45,"emoji":"🐉","power":91,"luck":88,"set":"Genesis X"},
    {"id":"l002","name":"Cosmic Shiba","rarity":"legendary","weight":45,"emoji":"🐕","power":92,"luck":94,"set":"Genesis X"},
    {"id":"l003","name":"King Nothing","rarity":"legendary","weight":45,"emoji":"👑","power":96,"luck":88,"set":"Genesis X"},
    {"id":"l004","name":"Lucky Error","rarity":"legendary","weight":45,"emoji":"🎲","power":89,"luck":98,"set":"Genesis X"},
    {"id":"m001","name":"ONE","rarity":"mythic","weight":10,"emoji":"◉","power":100,"luck":100,"set":"Mythic"},
    {"id":"m002","name":"The Last Pixel","rarity":"mythic","weight":10,"emoji":"💠","power":99,"luck":100,"set":"Mythic"},
]
RARITY_ORDER = {"common":1, "rare":2, "epic":3, "legendary":4, "mythic":5}
